### ISSUE TITLE
Preact support

### ISSUE THREAD

**Issue by JajarGaming** [yezyilomo/state-pool#171]
https://preactjs.com/

**Comment by yezyilomo** [comment]
There’s a big update coming soon that will include support for both Nextjs, Remix run and Preact. Stay tuned, we’ll a have section on documentation for integrating state-pool in both frameworks.

**Comment by JajarGaming** [comment]
v1.0.0?

**Comment by yezyilomo** [comment]
The next release might actually be the last 0.X release, we won’t go directly to 1.0.0 because we’ve introduced a lot of features so the API has changed massively but for good, so we’ll need a little time to fix issues that might come with the new APIs then after that I think we’ll go to 1.0.0

Just to give you a highlight, the next release is going to have these 
- #160
- #161 
- #162 
- #163 
- #164 
- #165 
- #166 
- #167 
- #168 

We’ve already implemented them, currently we’re working on documentation.

**Comment by JajarGaming** [comment]
👍🏼

**Comment by JajarGaming** [comment]
is preact supported now?
